### ISSUE TITLE
Erfasste Zeit wird berechnet bevor beide Werte ausgefüllt sind

### ISSUE THREAD

**Issue by Sandro-B** [SirKyomi/useitaIssues#9]
![grafik](https://github.com/SirKyomi/useitaIssues/assets/85075325/8e77895b-4842-4e76-aff9-120a73bd4311)
wenn man nur die Startzeit eingibt, sollte die noch nicht erfasste Zeit berechnet werden, die niemals negativ sein darf, und es sollte nicht möglich sein, dass die Startzeit später als die Endzeit ist

**Comment by SirKyomi** [comment]
in testing 0.0.1.0
